[programs.localnet]
saffle = "3QeRf38fdHBbaXqS87aMJjJtvRGzCvHbcXcHrmncMxpK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/gagebachik/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
